# Sauna 集成 — 调研结论: Sauna (by Wordware) 无公开 memory API; 集成方向是反的:
# Sauna 消费你提供的 MCP server ("Wire in any MCP server", sauna.ai/apps)。
# 所以这里做两件诚实的事:
#   1) 把记忆镜像成 Sauna 文档约定的 dual-memory workspace 结构 (sauna.ai/learn/memory):
#        workspace memory (durable, curated)  → sauna_export/ABOUT.md + memory/*.md
#        session memory  (episodic, indexed)  → sauna_export/sessions/*.md
#      —— 评委话术: "这就是 Sauna 描述的双记忆架构, 我们生成的就是它的 workspace 格式"
#   2) sauna_mcp.py 起 MCP server (:8902), Sauna 可直接接入查询学习记忆
# 界面徽章永远诚实: "local · Sauna-ready", 除非现场拿到真 API (SaunaStore._push 钩子保留位)。
import json
import socket
import time
from pathlib import Path

import memory as memmod

EXPORT = Path(__file__).resolve().parent.parent / "data" / "sauna_export"


def _w(rel: str, text: str):
    p = EXPORT / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text, encoding="utf-8")


def export_all(store) -> dict:
    """记忆 → Sauna workspace-memory 约定的 markdown。幂等, 每次全量重写 (小数据)。"""
    p = store.profile
    lv = memmod.level_of(p["skills"])
    lvp = memmod.xp_level(p["xp"])

    _w("ABOUT.md", f"""# {p.get('name') or 'Learner'} — spoken-English profile (fluent-me)

Level estimate: **{lv}** (from conversation scoring — CEFR-style, not a certified test)
XP {p['xp']} · Lv {lvp['lv']} · streak {p['streak']}d · {p['turns_total']} turns spoken
Skills: grammar {p['skills']['grammar']} · vocab {p['skills']['vocab']} · fluency {p['skills']['fluency']} · pron {p['skills']['pron']} (ASR proxy)
Native language: {p.get('native_lang') or 'unknown'}

Generated by fluent-me · updated {time.strftime('%Y-%m-%d %H:%M')}
""")

    facts_md = "\n".join(f"- {f['text']}  _(kind: {f.get('kind', 'other')}, since {time.strftime('%Y-%m-%d', time.localtime(f.get('ts', 0)))})_"
                         for f in p.get("facts", []) if f.get("use", True)) or "_(nothing yet)_"
    goals_md = "\n".join(f"- {g['kind']}: **{g['label']}** on {g.get('date') or 'TBD'}"
                         for g in p.get("goals", []) if g.get("active")) or "_(none)_"
    _w("memory/identity.md", f"""# Identity — what Fluent Me may use in conversation

## Facts (curated — the learner toggles these)
{facts_md}

## Goals
{goals_md}

## Words they want to learn
{', '.join(p.get('wishlist', [])) or '_(none)_'}
""")

    now = int(time.time())
    lines = ["# Mistake cards — spaced repetition (FSRS-inspired defaults, not a fitted model)", ""]
    for c in sorted(store.cards.values(), key=lambda c: c["status"] != "learning"):
        if c["status"] == "learning":
            r = memmod.retrievability(c, now)
            ex = c["examples"][-1] if c["examples"] else {"wrong": "", "right": ""}
            lines.append(f"- `{c['pattern']}` — {c['label']} · missed {c['hits']}x · "
                         f"memory strength ~{round(r * 100)}% · next review "
                         f"{time.strftime('%m-%d %H:%M', time.localtime(c['due_at']))} · "
                         f"\"{ex['wrong']}\" → \"{ex['right']}\"")
    grads = [c for c in store.cards.values() if c["status"] == "graduated"]
    if grads:
        lines += ["", "## Graduated (beaten for good)"]
        lines += [f"- `{c['pattern']}` — {c['label']}" for c in grads]
    _w("memory/mistake-cards.md", "\n".join(lines) + "\n")

    for e in store.episodes[-20:]:
        stamp = time.strftime("%Y-%m-%d-%H%M", time.localtime(e.get("ts", now)))
        facts = "\n".join(f"- {x.get('text', x) if isinstance(x, dict) else x}" for x in e.get("facts", []))
        _w(f"sessions/{stamp}.md", f"""# Session {e.get('date', stamp)}

{e.get('summary', '')}

Topics: {', '.join(e.get('topics', []))}
{'Best line: "' + e['best_moment'] + '"' if e.get('best_moment') else ''}

## Facts learned
{facts or '_(none)_'}
""")

    files = sorted(str(f.relative_to(EXPORT)) for f in EXPORT.rglob("*.md"))
    meta = {"exported_at": now, "files": files}
    _w("_meta.json", json.dumps(meta))
    return meta


def status() -> dict:
    meta = {}
    mp = EXPORT / "_meta.json"
    if mp.exists():
        try:
            meta = json.loads(mp.read_text())
        except json.JSONDecodeError:
            meta = {}
    s = socket.socket()
    s.settimeout(0.2)
    try:
        s.connect(("127.0.0.1", 8902))
        mcp_up = True
    except OSError:
        mcp_up = False
    finally:
        s.close()
    return {"exported_at": meta.get("exported_at"), "files": meta.get("files", []),
            "mcp_running": mcp_up, "mcp_port": 8902,
            "note": "local · Sauna-ready (Sauna has no public memory API; it consumes MCP servers — connect this one)"}
